### PR TITLE
Deploy CSV to JSON browser script into `gh-pages` and restyling it

### PR DESCRIPTION
**Pull request by IsmaCortGtz**
# Deploy CSV to JSON browser script into `gh-pages` and restyling it

This PR should help for the issue [#7](https://github.com/thealphadollar/vanilla-i18n/issues/7).

I added the implementation of my Browser runnable script for the issue [#3](https://github.com/thealphadollar/vanilla-i18n/issues/3), it can be accesed at the gh-page by a button, [see the example here](https://ismacortgtz.github.io/vanilla-i18n/).

imagen

I changed the structure of many files in the docs/ folder. It to imrpove the scalability and the organization of the site.

And probably the most evident change, I add a styling of the page with some CSS rules, taking as principal color the image of the logo.

Again, you can see the result in my deploy [here](https://ismacortgtz.github.io/vanilla-i18n/) and test it if you want. 😁

I was testing with your repo and I think the `gh-pages` are deployed in the `test_network` branch. So maybe you have to change it if you accept this PR.

### CODE REVIEW

**Comment by thealphadollar** [comment]
Looks amazing! Thank you so much for the great work @IsmaCortGtz I especially like the styling contribution 💯 

I have a small concern, I tried the demo and the button to download a single file wasn't working for me. Can you check if you can reproduce the error and then fix it? The button to download the entire zip is working perfectly.

image

**Comment by IsmaCortGtz** [comment]
Sure, I will check it.  😉

**Comment by IsmaCortGtz** [comment]
Hi @thealphadollar. 👋

Now it works for me. I changed the API of the library but I forgot to update the usage in the web.

I have some bugs with service workers in my other `gh-pages` repos so maybe you could need to check If the older version is cached.

Tell me if you need something else.

**Comment by thealphadollar** [comment]
Thanks for the quick changes, man. 

I'll have a look later tonight.

**Review by thealphadollar — APPROVED** [review]

**Pull request merged**
